---
# 标题

title: "[领地系统]"

#圈地工具
landTool: "290:0"

# 圈地时每个方块的价格
landMoney: 10.0

# 子领地每个方块价格
subLandMoney: 5.0

# 出售领地时 减少的价格百分比
# 这里的 50 是减少原价格的 50%
sellMoney: 50

# 黑名单世界
# 在此名单的世界无法圈地 OP 除外
# 示例: blackList: ["世界1","世界2"]
blackList: ["世界1","世界2"]

# 无权限的时候是否提示
echoPermission: true

# 在黑名单世界是否提示
echoBlackListMessage: true

# 保护世界
# 在此名单的世界无法破坏放置 需要圈地
# 示例: protectList: ["世界1","世界2"]
protectList: ["世界1","世界2"]

# 是否提示
echoProtectListMessage: true

# 限制玩家拥有的领地上限
# 注: 只拥有成员权限也计算在内
max: 5

# 限制子领地上限
subMax: 3

# 设置领地显示范围时间
time: 5

#公示期(天)
售卖领地显示时间: 7

# 加载的经济核心
#当前支持 EconomyAPI,Money,PlayerPoint
# default 为自动识别
loadEconomy: default

#领地传送时间相关设置
#time: 传送时间
# cold: 冷却时间
transfer-time-setting:
  enable: true
  time: 5
  cold: 30

#单位： 分钟
#领地自动保存设置
auto-save-land:
  open: true
  time: 30







...